name: dmfm
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Core
  - python>=3.9,<3.10
  - bokeh>=2.4.2
  - holoviews>=1.14.8
  - matplotlib>=3.3.2
  - numpy==1.21.5
  - pandas>=1.3.5,<1.4
  - panel>=0.12.7
  - scikit-learn>=0.24.1
  - scipy==1.7.3
  - seaborn>=0.11.2
  - tqdm>=4.63.0
  - rpy2>=3.5.10
  # R package
  - r-base
  - r-essentials
  - r-forecast
  - r-tidyverse
  # Testing
  - black>=22.3.0
  - flake8>=3.9.2,<4
  - hypothesis>=6.41.0
  - isort>=5.10.1
  - mypy>=0.942
  - nb-clean>=2.1.0
  - nbqa>=1.3.1
  - pandas-stubs>=1.2.0.56,<=1.2.0.62
  - pydocstyle>=6.1.1
  - pytest>=6.2.5,<7
  - pytest-flake8>=1.1.0
  # Nice to haves
  - ipykernel>=6.12.0
  - ipywidgets<=7.7.1
  - notebook>=6.4.10
  # atd2022 and other misc. dependencies
  - pip>=22.0.4
  - pip:
    - -e .[all]
